# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Burak Hamza
email: burak@burakhamza.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.burakhamza.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: datcal
github_username:  datcal

# Build settings
#minima
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

skin: "/assets/css/skins/dark.css"
locale: en-US
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "G-10Y3YH8QZT"
disqus:
  shortname: "datcal"
twitter:
  username: "datcal"

mathjax:
  enable: true

# Liquid
liquid:
  error_mode: strict

# Search
search_full_content: false

comments: true

# Build settings
markdown: kramdown
feed:
  path: atom.xml

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

copyright: ''

# Site Author
# Site Author
author:
  name: Burak Hamza
  picture: /images/datcal.jpeg
  email: burak@burahamza.com
  twitter: datcal
  links:
    - title: Twitter
      url: https://twitter.com/datcal
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/datcalhombre
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/datcal
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/datcal
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/datcalhombre
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/datcal
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square   
